config/routes.rb
class SubdomainConstraint
	def self.matches?(request)
		subdomains=%{www}
		request.subdomain.present? && !subdomains.include?(request.subdomain)
	end
end
Rails.application.routes.draw do

  resources :projects
  resources :projects
  resources :projects
  constraints SubdomainConstraint do
    get 'project_management',to:'project_management#index'
    root to: 'dashboard#index'
    resources :users
    devise_for :users ,:path => 'accounts'
    resources :cost_books
    get 'cost_books/:cost_book_id/analysis_of_rate/:id', 
    to: 'cost_books#analysis_of_rate',as: 'analysis_of_rate'
    patch 'cost_books/:id/update_schedule_item', 
    to: 'cost_books#update_schedule_item',as: 'update_schedule_item'
    resources :resources
    resources :schedule_of_works
    resources :units
    resources :roles
  end
  get '/', to:'visitors#index'
  get 'register', to:'register#index'
  get 'registration_complete', to:'register#complete'
  post 'register', to:'register#create'
  # root to: 'visitors#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

   def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :role
  belongs_to :permission
end

app/models/cost_book.rb
class CostBook < ActiveRecord::Base
  belongs_to :schedule_of_work
  has_many :cost_book_schedule_items
  has_many :schedule_of_works_items, :through => :cost_book_schedule_items, 
  :dependent => :destroy
  	accepts_nested_attributes_for :schedule_of_works_items, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/over_head.rb
class OverHead < ActiveRecord::Base
  belongs_to :cost_book_schedule_item
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_many :assignments
  has_many :roles, 
           :through => :assignments
end

app/models/permission_role.rb
class PermissionRole < ActiveRecord::Base
  belongs_to :role
  belongs_to :permission
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :cost_book
	has_many :project_schedule_items
	has_many :cost_book_schedule_items, :through => :project_schedule_items, 
	:dependent => :destroy
	accepts_nested_attributes_for :cost_book_schedule_items, 
	:reject_if => :all_blank, 
	:allow_destroy => true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  enum resource_type: [:material, :equipment, :labor,:other]
  belongs_to :unit
end

app/models/role.rb
class Role < ActiveRecord::Base
	 has_many :assignments
  has_many :permissions, 
           :through => :assignments
  accepts_nested_attributes_for :permissions, allow_destroy: true, reject_if: :all_blank
end

app/models/schedule_of_work.rb
class ScheduleOfWork < ActiveRecord::Base
	has_many :sections
	accepts_nested_attributes_for :sections, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :schedule_of_work
  	has_many :schedule_of_works_items
	accepts_nested_attributes_for :schedule_of_works_items, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
	after_create :create_tenant
  attr_accessor :email, :password
  belongs_to :plan
  belongs_to :user
  private

  def create_tenant
  	Apartment::Tenant.create(subdomain)
  	Apartment::Tenant.switch!(subdomain)
  	 	user = User.new(:email => email, 
  		:password => password, :password_confirmation => password)
  		user.save
  		update_attribute(:user,@user)
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  #enum role: [:user, :vip, :admin]
  #after_initialize :set_default_role, :if => :new_record?

  # def set_default_role
  #   self.role ||= :user
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/schedule_of_works_controller.rb
class ScheduleOfWorksController < ProjectsBaseController
  before_action :set_schedule_of_work, only: [:show, :edit, :update, :destroy]

  # GET /schedule_of_works
  # GET /schedule_of_works.json
  def index
    @schedule_of_works = ScheduleOfWork.all
  end

  # GET /schedule_of_works/1
  # GET /schedule_of_works/1.json
  def show
  end

  # GET /schedule_of_works/new
  def new
    @schedule_of_work = ScheduleOfWork.new
  end

  # GET /schedule_of_works/1/edit
  def edit
  end

  # POST /schedule_of_works
  # POST /schedule_of_works.json
  def create
    @schedule_of_work = ScheduleOfWork.new(schedule_of_work_params)

    respond_to do |format|
      if @schedule_of_work.save
        format.html { redirect_to @schedule_of_work, notice: 'Schedule of work was successfully created.' }
        format.json { render :show, status: :created, location: @schedule_of_work }
      else
        format.html { render :new }
        format.json { render json: @schedule_of_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedule_of_works/1
  # PATCH/PUT /schedule_of_works/1.json
  def update
    respond_to do |format|
      if @schedule_of_work.update(schedule_of_work_params)
        format.html { redirect_to @schedule_of_work, notice: 'Schedule of work was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule_of_work }
      else
        format.html { render :edit }
        format.json { render json: @schedule_of_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_of_works/1
  # DELETE /schedule_of_works/1.json
  def destroy
    @schedule_of_work.destroy
    respond_to do |format|
      format.html { redirect_to schedule_of_works_url, notice: 'Schedule of work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule_of_work
      @schedule_of_work = ScheduleOfWork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_of_work_params
      params.require(:schedule_of_work).permit(:name, :description,
        sections_attributes:[:id,:name,:description,:_destroy,
          schedule_of_works_items_attributes:[:id,:name,
            :price,:unit_id,:premium,:unitMultiplier,:displayUnit,
            :description,:remarks,:_destroy]])
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schedule_of_works_helper.rb
module ScheduleOfWorksHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/schedule_of_works/_form.html.erb
<%= simple_form_for(@schedule_of_work,:html=>{:class=>"form-compact"}) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <h3>Items</h3>
    <div id="tasks">
      <%= f.simple_fields_for :sections do |task| %>
        <%= render 'section_fields', :f => task %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add section', f, :sections %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/schedule_of_works/_schedule_of_works_item_fields.html.erb
<hr>
<div class="nested-fields row">
 <%= f.input :name,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'} %>
   
  <%= f.association :unit, :wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'}%>
  <%= f.input :price,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'} %>
  <%= f.input :premium,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'} %>
  <%= f.input :unitMultiplier,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'} %>
  <%= f.input :displayUnit,:wrapper_html =>{:class=>'col-md-1 col-sm-2 col-xs-3'} %>
 <%= f.input :description,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'} %>
   <%= f.input :remarks ,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'}%>
  <div class="form-group col-md-2 col-sm-4 col-xs-6">
        <label for="ssn">Add</label><br>
          <%= link_to_remove_association "remove item", f ,:class=>"btn btn-primary btn-xs"%>
      </div>

</div>

app/views/schedule_of_works/_section_fields.html.erb
<hr>
<div class="nested-fields table-bg-accent row">
 <%= f.input :name,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'} %>
 <%= f.input :description,:wrapper_html =>{:class=>'col-md-4 col-sm-6 col-xs-8'} %>
  <div class="form-group col-md-2 col-sm-4 col-xs-6">
        <label for="ssn">Add</label><br>
          <%= link_to_remove_association "remove item", f ,:class=>"btn btn-primary btn-xs"%>
      </div>
      <div class="form-group col-md-2 col-sm-4 col-xs-6">
        <label for="ssn">Toggle</label><br>
        <a onclick="alert('hello')" class="btn btn-primary btn-xs">Collapse</a>
      </div>
</div>
  <div class="container row">
      <%= f.simple_fields_for :schedule_of_works_items do |task| %>
        <%= render 'schedule_of_works_item_fields', :f => task %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add item', f, :schedule_of_works_items %>
      </div>
    </div>

app/views/schedule_of_works/edit.html.erb
<h1>Editing Schedule of works</h1>
<%= render 'form' %>
<%= link_to 'Show', @schedule_of_work %>
\|
<%= link_to 'Back', schedule_of_works_path %>

app/views/schedule_of_works/index.html.erb
<h1>Listing schedule of works</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @schedule_of_works.each do |schedule_of_work| %>
      <tr>
        <td>
          <%= schedule_of_work.name %>
        </td>
        <td>
          <%= schedule_of_work.description %>
        </td>
        <td>
          <%= link_to 'Show', schedule_of_work %>
        </td>
        <td>
          <%= link_to 'Edit', edit_schedule_of_work_path(schedule_of_work) %>
        </td>
        <td>
          <%= link_to 'Destroy', schedule_of_work, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Schedule of work', new_schedule_of_work_path %>

app/views/schedule_of_works/new.html.erb
<h1>New Schedule of works</h1>
<%= render 'form' %>
<%= link_to 'Back', schedule_of_works_path %>

app/views/schedule_of_works/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <b>Name:</b>
  <%= @schedule_of_work.name %>
</p>
<p>
  <b>Description:</b>
  <%= @schedule_of_work.description %>
</p>
<%= link_to 'Edit', edit_schedule_of_work_path(@schedule_of_work) %>
\|
<%= link_to 'Back', schedule_of_works_path %>