config/routes.rb
class SubdomainConstraint
	def self.matches?(request)
		subdomains=%{www}
		request.subdomain.present? && !subdomains.include?(request.subdomain)
	end
end
Rails.application.routes.draw do

  resources :projects
  resources :projects
  resources :projects
  constraints SubdomainConstraint do
    get 'project_management',to:'project_management#index'
    root to: 'dashboard#index'
    resources :users
    devise_for :users ,:path => 'accounts'
    resources :cost_books
    get 'cost_books/:cost_book_id/analysis_of_rate/:id', 
    to: 'cost_books#analysis_of_rate',as: 'analysis_of_rate'
    patch 'cost_books/:id/update_schedule_item', 
    to: 'cost_books#update_schedule_item',as: 'update_schedule_item'
    resources :resources
    resources :schedule_of_works
    resources :units
    resources :roles
  end
  get '/', to:'visitors#index'
  get 'register', to:'register#index'
  get 'registration_complete', to:'register#complete'
  post 'register', to:'register#create'
  # root to: 'visitors#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

   def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :role
  belongs_to :permission
end

app/models/cost_book.rb
class CostBook < ActiveRecord::Base
  belongs_to :schedule_of_work
  has_many :cost_book_schedule_items
  has_many :schedule_of_works_items, :through => :cost_book_schedule_items, 
  :dependent => :destroy
  	accepts_nested_attributes_for :schedule_of_works_items, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/over_head.rb
class OverHead < ActiveRecord::Base
  belongs_to :cost_book_schedule_item
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_many :assignments
  has_many :roles, 
           :through => :assignments
end

app/models/permission_role.rb
class PermissionRole < ActiveRecord::Base
  belongs_to :role
  belongs_to :permission
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :cost_book
	has_many :project_schedule_items
	has_many :cost_book_schedule_items, :through => :project_schedule_items, 
	:dependent => :destroy
	accepts_nested_attributes_for :cost_book_schedule_items, 
	:reject_if => :all_blank, 
	:allow_destroy => true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  enum resource_type: [:material, :equipment, :labor,:other]
  belongs_to :unit
end

app/models/role.rb
class Role < ActiveRecord::Base
	 has_many :assignments
  has_many :permissions, 
           :through => :assignments
  accepts_nested_attributes_for :permissions, allow_destroy: true, reject_if: :all_blank
end

app/models/schedule_of_work.rb
class ScheduleOfWork < ActiveRecord::Base
	has_many :sections
	accepts_nested_attributes_for :sections, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :schedule_of_work
  	has_many :schedule_of_works_items
	accepts_nested_attributes_for :schedule_of_works_items, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
	after_create :create_tenant
  attr_accessor :email, :password
  belongs_to :plan
  belongs_to :user
  private

  def create_tenant
  	Apartment::Tenant.create(subdomain)
  	Apartment::Tenant.switch!(subdomain)
  	 	user = User.new(:email => email, 
  		:password => password, :password_confirmation => password)
  		user.save
  		update_attribute(:user,@user)
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  #enum role: [:user, :vip, :admin]
  #after_initialize :set_default_role, :if => :new_record?

  # def set_default_role
  #   self.role ||= :user
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cost_books_controller.rb
class CostBooksController < ProjectsBaseController
  before_action :set_cost_book, only: [:show, :edit, :update, :destroy]

  # GET /cost_books
  # GET /cost_books.json
  def index
    @cost_books = CostBook.all
  end

  # GET /cost_books/1
  # GET /cost_books/1.json
  def show
  end

  # GET /cost_books/new
  def new
    @cost_book = CostBook.new
  end

  # GET /cost_books/1/edit
  def edit
  end

  def analysis_of_rate
    @item = CostBookScheduleItem.where(:schedule_of_works_item_id=>params[:id]).take
  end

  def update_schedule_item
    @item = CostBookScheduleItem.where(:schedule_of_works_item_id=>params[:id]).take
    @item.created_at = Time.now
    respond_to do |format|
      if @item.update(cost_book_item_params)
        format.html { redirect_to :back, notice: 'Cost book was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { redirect_to :back }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /cost_books
  # POST /cost_books.json
  def create
    @cost_book = CostBook.new(cost_book_params)

    respond_to do |format|
      if @cost_book.save
        format.html { redirect_to @cost_book, notice: 'Cost book was successfully created.' }
        format.json { render :show, status: :created, location: @cost_book }
      else
        format.html { render :new }
        format.json { render json: @cost_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cost_books/1
  # PATCH/PUT /cost_books/1.json
  def update
    respond_to do |format|
      if @cost_book.update(cost_book_params)
        format.html { redirect_to @cost_book, notice: 'Cost book was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost_book }
      else
        format.html { render :edit }
        format.json { render json: @cost_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cost_books/1
  # DELETE /cost_books/1.json
  def destroy
    @cost_book.destroy
    respond_to do |format|
      format.html { redirect_to cost_books_url, 
        notice: 'Cost book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost_book
      @cost_book = CostBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_book_params
      params.require(:cost_book).permit(:name, :specification, :remarks,
       :schedule_of_work_id,:schedule_of_works_item_ids=>[])
    end
      def cost_book_item_params
    params.require(:cost_book_schedule_item).permit(cost_book_item_resources_attributes: [:id, 
      :resource_id, :quantity, :_destroy],over_heads_attributes: [:id, 
      :description, :percentage, :_destroy])
  end
end

app/helpers/cost_books_helper.rb
module CostBooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cost_books/_cost_book_item_resource_fields.html.erb
<div class="nested-fields row">
  <%= f.association :resource ,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'}%>
  <%= f.input :quantity,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'} %>
   
   <div class="form-group col-md-2 col-sm-4 col-xs-6">
   <label for="ssn">Price</label><br>
   <%if f.object.resource%>
   <input class="form-control col-md-2 col-sm-4 col-xs-6" type="text" readonly="true" value="<%=f.object.resource.price %>/<%=f.object.resource.unit.name %>" >
    <%end%>
  </div>


   <div class="form-group col-md-2 col-sm-4 col-xs-6">
   <label for="ssn">Total</label><br>
   <%if f.object.total%>
  <input class="form-control col-md-2 col-sm-4 col-xs-6" type="text" readonly="true" value="<%=f.object.total %>" >
    <%end%>
  </div>

  <div class="form-group col-md-2 col-sm-4 col-xs-6">
        <label for="ssn">Remove</label><br>
          <%= link_to_remove_association "remove item", f ,:class=>"btn btn-primary btn-xs"%>
      </div>
</div>

app/views/cost_books/_form.html.erb
<%= simple_form_for(@cost_book) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :specification %>
    <%= f.input :remarks %>
    <%= f.association :schedule_of_work %>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cost_books/_over_head_fields.html.erb
<div class="nested-fields row">
  <%= f.input :description ,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'}%>
  <%= f.input :percentage,:wrapper_html =>{:class=>'col-md-2 col-sm-4 col-xs-6'} %>
   <div class="form-group col-md-2 col-sm-4 col-xs-6">
   <label for="ssn">Total</label><br>
   <%if f.object.total%>
  <input class="form-control col-md-2 col-sm-4 col-xs-6" type="text" readonly="true" value="<%=f.object.total %>" >
    <%end%>
  </div>

  <div class="form-group col-md-2 col-sm-4 col-xs-6">
        <label for="ssn">Remove</label><br>
          <%= link_to_remove_association "remove item", f ,:class=>"btn btn-primary btn-xs"%>
      </div>
</div>

app/views/cost_books/analysis_of_rate.html.erb
<p> Analysis of rates of <%=@item.schedule_of_works_item.name%> <%=@item.schedule_of_works_item.description%> for cost book <%=@item.cost_book.name%></p>
<h2>Resources to make 1 <%=@item.schedule_of_works_item.unit.name%> of <%=@item.schedule_of_works_item.description%></h2>
<%= simple_form_for  @item,:html=>{:class=>"form-compact"},:url=>update_schedule_item_path do |f| %>
<div class="form-inputs">
  <div id="tasks">
    <%= f.simple_fields_for :cost_book_item_resources do |task| %>
      <%= render 'cost_book_item_resource_fields', :f => task %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add resource', f, :cost_book_item_resources %>
    </div>
    <div class="container row">
      <span>Total Resource Costs:<%= @item.total_cost_book_item_resources %></span>
    </div>
     <%= f.simple_fields_for :over_heads do |task| %>
      <%= render 'over_head_fields', :f => task %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add overhead', f, :over_heads %>
    </div>
    <div class="container row">
      <span>Total Overhead Costs:<%= @item.total_over_heads %></span>
    </div>

  </div>
  </div>
   <div class="container row">
      <span>Total Costs:<%= @item.cost_totals %></span>
    </div>
   <div class="form-actions">
  <%= f.button :submit %>
  </div>
<% end %>
<%= link_to 'Back to costbook', edit_cost_book_path(:id=>params[:cost_book_id]) %>

app/views/cost_books/edit.html.erb
<h1>Editing Cost Book</h1>

<%= simple_form_for(@cost_book) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
	<%= f.input :name %>
	<%= f.input :specification %>
	<%= f.input :remarks %>
	<%= f.association :schedule_of_work %>
	<h2>Please Select Schedule of Works to Include In this cost Book</h2>
	<table class="table">
<thead>
			<th>
				Name
			</th>
			<th>
				Description

			</th>
			<th>
				

			</th>
			<th>
				Stated Price

			</th>
			<th>
				Analysed Price

			</th>
			<th>
				

			</th>
		</thead>
		<% @cost_book.schedule_of_work.sections.each do |section| %>
		<thead>
			<th>
				<%= section.name %>

			</th>
			<th>
				<%= section.description %>

			</th>
			<th>
				

			</th>
			<th>
				

			</th>
			<th>
				
<th>
				

			</th>
			</th>
		</thead>
		<% section.schedule_of_works_items.each do |item| %>
		<tr>
			<td>
				<%= check_box_tag "cost_book[schedule_of_works_item_ids][]",item.id,@cost_book.schedule_of_works_item_ids.include?(item.id) %>
			</td>
			<td>
				<%= item.name %>
			</td>
			<td>
				<%= item.description %>
			</td>
			<td>
				<%= item.price %>
			</td>
			<td>
				<%= item.cost_book_item.cost_totals %>
			</td>
						<td>
				<%if @cost_book.schedule_of_works_item_ids.include?(item.id) %>
				<%=link_to "Analysis Rates",analysis_of_rate_path(:cost_book_id=>@cost_book.id,:id => item.id),{ :class=>"btn btn-primary btn-xs" } %>
								<%end%>
							</td>
		</tr>
		<% end %>
		<% end %>
	</table>
</div>
<div class="form-actions">
	<%= f.button :submit %>
</div>
<% end %>

<%= link_to 'Show', @cost_book %> |
<%= link_to 'Back', cost_books_path %>

app/views/cost_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cost Books</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Specification</th>
      <th>Remarks</th>
      <th>Schedule of work</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cost_books.each do |cost_book| %>
      <tr>
        <td><%= cost_book.name %></td>
        <td><%= cost_book.specification %></td>
        <td><%= cost_book.remarks %></td>
        <td><%= cost_book.schedule_of_work.name %></td>
        <td><%= link_to 'Show', cost_book %></td>
        <td><%= link_to 'Edit', edit_cost_book_path(cost_book) %></td>
        <td><%= link_to 'Destroy', cost_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost book', new_cost_book_path %>

app/views/cost_books/new.html.erb
<h1>New Cost Book</h1>

<%= render 'form' %>

<%= link_to 'Back', cost_books_path %>

app/views/cost_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cost_book.name %>
</p>

<p>
  <strong>Specification:</strong>
  <%= @cost_book.specification %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @cost_book.remarks %>
</p>

<p>
  <strong>Schedule of work:</strong>
  <%= @cost_book.schedule_of_work %>
</p>

<%= link_to 'Edit', edit_cost_book_path(@cost_book) %> |
<%= link_to 'Back', cost_books_path %>