config/routes.rb
class SubdomainConstraint
	def self.matches?(request)
		subdomains=%{www}
		request.subdomain.present? && !subdomains.include?(request.subdomain)
	end
end
Rails.application.routes.draw do

  resources :projects
  resources :projects
  resources :projects
  constraints SubdomainConstraint do
    get 'project_management',to:'project_management#index'
    root to: 'dashboard#index'
    resources :users
    devise_for :users ,:path => 'accounts'
    resources :cost_books
    get 'cost_books/:cost_book_id/analysis_of_rate/:id', 
    to: 'cost_books#analysis_of_rate',as: 'analysis_of_rate'
    patch 'cost_books/:id/update_schedule_item', 
    to: 'cost_books#update_schedule_item',as: 'update_schedule_item'
    resources :resources
    resources :schedule_of_works
    resources :units
    resources :roles
  end
  get '/', to:'visitors#index'
  get 'register', to:'register#index'
  get 'registration_complete', to:'register#complete'
  post 'register', to:'register#create'
  # root to: 'visitors#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

   def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :role
  belongs_to :permission
end

app/models/cost_book.rb
class CostBook < ActiveRecord::Base
  belongs_to :schedule_of_work
  has_many :cost_book_schedule_items
  has_many :schedule_of_works_items, :through => :cost_book_schedule_items, 
  :dependent => :destroy
  	accepts_nested_attributes_for :schedule_of_works_items, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/over_head.rb
class OverHead < ActiveRecord::Base
  belongs_to :cost_book_schedule_item
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_many :assignments
  has_many :roles, 
           :through => :assignments
end

app/models/permission_role.rb
class PermissionRole < ActiveRecord::Base
  belongs_to :role
  belongs_to :permission
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :cost_book
	has_many :project_schedule_items
	has_many :cost_book_schedule_items, :through => :project_schedule_items, 
	:dependent => :destroy
	accepts_nested_attributes_for :cost_book_schedule_items, 
	:reject_if => :all_blank, 
	:allow_destroy => true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  enum resource_type: [:material, :equipment, :labor,:other]
  belongs_to :unit
end

app/models/role.rb
class Role < ActiveRecord::Base
	 has_many :assignments
  has_many :permissions, 
           :through => :assignments
  accepts_nested_attributes_for :permissions, allow_destroy: true, reject_if: :all_blank
end

app/models/schedule_of_work.rb
class ScheduleOfWork < ActiveRecord::Base
	has_many :sections
	accepts_nested_attributes_for :sections, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :schedule_of_work
  	has_many :schedule_of_works_items
	accepts_nested_attributes_for :schedule_of_works_items, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
	after_create :create_tenant
  attr_accessor :email, :password
  belongs_to :plan
  belongs_to :user
  private

  def create_tenant
  	Apartment::Tenant.create(subdomain)
  	Apartment::Tenant.switch!(subdomain)
  	 	user = User.new(:email => email, 
  		:password => password, :password_confirmation => password)
  		user.save
  		update_attribute(:user,@user)
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  #enum role: [:user, :vip, :admin]
  #after_initialize :set_default_role, :if => :new_record?

  # def set_default_role
  #   self.role ||= :user
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/projects_controller.rb
class ProjectsController < ProjectsBaseController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :cost_book_id,:cost_book_schedule_item_ids=>[])
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :cost_book %>
  </div>
   <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= simple_form_for(@project) do |f| %>
<div class="form-inputs">
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.association :cost_book %>
</div>
<table class="table">
	<thead>
	<th></th>
		<th>
			Name
		</th>
		<th>
			Description

		</th>
		<th>
			Section

		</th>
		<th>
			Price

		</th>
	</thead>
	<tbody>
	<%@project.cost_book.cost_book_schedule_items.each do |item|%>
	<tr>
		<td>
			<%= check_box_tag "project[cost_book_schedule_item_ids][]",item.id,@project.cost_book_schedule_item_ids.include?(item.id) %>
		</td>
		<td>
			<%= item.schedule_of_works_item.name %>
		</td>
		<td>
			<%= item.schedule_of_works_item.description %>
		</td>
		<td>
			<%= item.schedule_of_works_item.section.description %>
		</td>
		<td>
			<%= item.cost_totals %>
		</td>
	</tr>	
	<%end%>
	</tbody>
</table>
<div class="form-actions">
	<%= f.button :submit %>
</div>
<% end %>
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Cost book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.cost_book.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Cost book:</strong>
  <%= @project.cost_book %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>