config/routes.rb
class SubdomainConstraint
	def self.matches?(request)
		subdomains=%{www}
		request.subdomain.present? && !subdomains.include?(request.subdomain)
	end
end
Rails.application.routes.draw do

  resources :projects
  resources :projects
  resources :projects
  constraints SubdomainConstraint do
    get 'project_management',to:'project_management#index'
    root to: 'dashboard#index'
    resources :users
    devise_for :users ,:path => 'accounts'
    resources :cost_books
    get 'cost_books/:cost_book_id/analysis_of_rate/:id', 
    to: 'cost_books#analysis_of_rate',as: 'analysis_of_rate'
    patch 'cost_books/:id/update_schedule_item', 
    to: 'cost_books#update_schedule_item',as: 'update_schedule_item'
    resources :resources
    resources :schedule_of_works
    resources :units
    resources :roles
  end
  get '/', to:'visitors#index'
  get 'register', to:'register#index'
  get 'registration_complete', to:'register#complete'
  post 'register', to:'register#create'
  # root to: 'visitors#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

   def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user.role.permissions.each do |permission|
      if permission.subject_class == "all"
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :role
  belongs_to :permission
end

app/models/cost_book.rb
class CostBook < ActiveRecord::Base
  belongs_to :schedule_of_work
  has_many :cost_book_schedule_items
  has_many :schedule_of_works_items, :through => :cost_book_schedule_items, 
  :dependent => :destroy
  	accepts_nested_attributes_for :schedule_of_works_items, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/over_head.rb
class OverHead < ActiveRecord::Base
  belongs_to :cost_book_schedule_item
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_many :assignments
  has_many :roles, 
           :through => :assignments
end

app/models/permission_role.rb
class PermissionRole < ActiveRecord::Base
  belongs_to :role
  belongs_to :permission
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :cost_book
	has_many :project_schedule_items
	has_many :cost_book_schedule_items, :through => :project_schedule_items, 
	:dependent => :destroy
	accepts_nested_attributes_for :cost_book_schedule_items, 
	:reject_if => :all_blank, 
	:allow_destroy => true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  enum resource_type: [:material, :equipment, :labor,:other]
  belongs_to :unit
end

app/models/role.rb
class Role < ActiveRecord::Base
	 has_many :assignments
  has_many :permissions, 
           :through => :assignments
  accepts_nested_attributes_for :permissions, allow_destroy: true, reject_if: :all_blank
end

app/models/schedule_of_work.rb
class ScheduleOfWork < ActiveRecord::Base
	has_many :sections
	accepts_nested_attributes_for :sections, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :schedule_of_work
  	has_many :schedule_of_works_items
	accepts_nested_attributes_for :schedule_of_works_items, 
           :reject_if => :all_blank, 
           :allow_destroy => true
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
	after_create :create_tenant
  attr_accessor :email, :password
  belongs_to :plan
  belongs_to :user
  private

  def create_tenant
  	Apartment::Tenant.create(subdomain)
  	Apartment::Tenant.switch!(subdomain)
  	 	user = User.new(:email => email, 
  		:password => password, :password_confirmation => password)
  		user.save
  		update_attribute(:user,@user)
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  #enum role: [:user, :vip, :admin]
  #after_initialize :set_default_role, :if => :new_record?

  # def set_default_role
  #   self.role ||= :user
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/resources/_form.html.erb
<%= simple_form_for(@resource) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :specification %>
    <%= f.input :resource_type , :as => :select, :collection => Resource.resource_types.keys.to_a %>
    <%= f.association :unit %>
    <%= f.input :price %>
    <%= f.input :remarks %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Specification</th>
      <th>Type</th>
      <th>Unit</th>
      <th>Price</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.specification %></td>
        <td><%= resource.resource_type %></td>
        <td><%= resource.unit.name %></td>
        <td><%= resource.price %></td>
        <td><%= resource.remarks %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Specification:</strong>
  <%= @resource.specification %>
</p>

<p>
  <strong>Type:</strong>
  <%= @resource.resource_type %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @resource.unit %>
</p>

<p>
  <strong>Price:</strong>
  <%= @resource.price %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @resource.remarks %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>